version: '3'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    tty: true
    networks:
      - nodenetwork
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s /usr/src/entrypoint.sh
    networks:
      - nodenetwork
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - nodenetwork

networks:
  nodenetwork:
      driver: bridge